# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
    container_name: dbms_wed
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume3:/code/staticfiles  # Persist static files
      - media_volume2:/code/media    # Persist media files
      - ./db/db.sqlite3:/app/db.sqlite3 
    expose:
      - 8000:8000
  db:
    image: postgres:14
    container_name: training_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "$POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT"
  nginx:
    build: ./nginx
    volumes:
      - static_volume3:/code/staticfiles  # Share static files with Nginx
      - media_volume2:/code/media    # Share media files with Nginx
    ports:
      - "8086:80"  # Map external port 80 to Nginx port 80
    depends_on:
      - app

volumes:
  static_volume3:
  media_volume2:
  postgres_data: